# Generated by Django 2.0.9 on 2018-11-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='def.png', upload_to=''),
        ),
    ]
